packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  ccxt: true
  msgpackr-extract: true
  prisma: true
  sharp: true
